// Insaniquarium - Remastered Mod core: ddraw.dll proxy + mod loader + the API mods use (include/remod.h).
//
// The game loads DirectDraw at start-up with LoadLibrary("ddraw.dll"), which finds this DLL in the game folder first
// (Wine: set ddraw to native, WINEDLLOVERRIDES=ddraw=n,b). Every ddraw export jumps to the system's ddraw.dll (stubs
// generated by tools/gen-proxy.py). On load it checks that the exe is the one our addresses are for and installs the
// core hooks; the game's first DirectDrawCreate(Ex) call (main thread, during WinFishApp::Init, before resources load)
// then loads every mods/*.dll and calls its RemodInit before handing over to the real DirectDraw.
#include <windows.h>
#include <shlobj.h>
#include <setjmp.h>
#include <stdarg.h>
#include <stdio.h>
#include <string>
#include <vector>
#include <map>
#include "MinHook.h"
#include "remod.h"
#include "game.h"
#include "display.h"

extern "C" void* g_real[];
extern "C" void* const g_missing[];   // per-export E_NOTIMPL stand-ins with the right stack cleanup
extern "C" const char* const g_real_names[];
extern "C" const int g_real_count;

namespace {

std::string gGameDir, gModsDir;
FILE* gLog;
bool gActive;   // the exe matched: hooks and mods are on

// every callback remembers the mod that registered it, so a mod that crashes can be switched off
template <typename F> struct Cb { F fn; HMODULE owner; };
std::vector<Cb<void (*)(void*)>> gTick;
std::vector<Cb<void (*)(void*, void*)>> gDraw;
std::vector<Cb<int (*)(int, int)>> gKey;
std::vector<Cb<void (*)(void*)>> gOverlay;
std::vector<Cb<int (*)(int, int, int, int)>> gMouse;
std::vector<Cb<void (*)(void)>> gConfig;
int (*gInputFilter)(unsigned, unsigned, long);
HMODULE gInputFilterOwner;
int gMouseX, gMouseY;      // last pointer position in game coordinates
bool gSwallowUp[3];        // a mod took this button's press: keep its release from the game too
std::vector<HMODULE> gDisabled;   // mods switched off after a crash
struct ModInfo { std::string name, description; int state; HMODULE module; };
std::vector<ModInfo> gMods;
std::string gToast;
DWORD gToastUntil;   // GetTickCount() when the toast goes away (0: not shown yet)
bool gToastUntilInput;   // the toast stays until the player clicks or presses a key (the start-up message)
bool gToastTop;   // drawn at the top (the start-up message: at the bottom it would cover the title screen's "Click here to play!")
bool gRedraw;        // repaint everything at the next frame
WNDPROC gOrigWndProc;

void Log(const char* fmt, ...)
{
    if (!gLog) return;
    SYSTEMTIME t; GetLocalTime(&t);
    fprintf(gLog, "%02d:%02d:%02d ", t.wHour, t.wMinute, t.wSecond);
    va_list a; va_start(a, fmt); vfprintf(gLog, fmt, a); va_end(a);
    fputc('\n', gLog); fflush(gLog);
}

HMODULE ModuleOf(void* addr)
{
    HMODULE m = nullptr;
    GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS | GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT, (LPCSTR)addr, &m);
    return m;
}

std::string ModName(HMODULE m)
{
    char p[MAX_PATH] = "?";
    if (m) GetModuleFileNameA(m, p, MAX_PATH);
    std::string s = p;
    return s.substr(s.find_last_of("\\/") + 1);
}

bool Disabled(HMODULE m) { for (auto d : gDisabled) if (d == m) return true; return false; }
void Toast(const char* text);

// ---- crash containment ----------------------------------------------------------------------------------------
// Calls into mods run "guarded": if one faults (bad pointer, illegal instruction, divide by zero), a vectored exception
// handler sends execution back to the guard (longjmp), the mod is switched off for the session and the game goes on.
// (Faults inside a mod's own hooks of game functions can't be caught this way: they run as game code.)
jmp_buf* gGuard;
void* gFaultAddr;
DWORD gFaultCode;

extern "C" void __cdecl RecoverFromFault() { longjmp(*gGuard, 1); }

LONG CALLBACK FaultHandler(EXCEPTION_POINTERS* e)
{
    DWORD c = e->ExceptionRecord->ExceptionCode;
    bool fatal = c == EXCEPTION_ACCESS_VIOLATION || c == EXCEPTION_ILLEGAL_INSTRUCTION || c == EXCEPTION_PRIV_INSTRUCTION
              || c == EXCEPTION_INT_DIVIDE_BY_ZERO || c == EXCEPTION_ARRAY_BOUNDS_EXCEEDED;
    if (!gGuard || !fatal) return EXCEPTION_CONTINUE_SEARCH;
    gFaultAddr = e->ExceptionRecord->ExceptionAddress;
    gFaultCode = c;
    e->ContextRecord->Eip = (DWORD)(uintptr_t)&RecoverFromFault;
    return EXCEPTION_CONTINUE_EXECUTION;
}

void DisableMod(HMODULE m, const char* where)
{
    if (Disabled(m)) return;
    gDisabled.push_back(m);
    HMODULE at = ModuleOf(gFaultAddr);
    Log("%s crashed in %s (code %08lx at %p in %s) and was switched off for this session",
        ModName(m).c_str(), where, gFaultCode, gFaultAddr, ModName(at).c_str());
    std::string t = ModName(m) + " crashed and was switched off";
    Toast(t.c_str());
    for (auto& mi : gMods) if (mi.module == m) mi.state = REMOD_MOD_CRASHED;
}

template <typename F> bool Guarded(HMODULE owner, const char* where, F&& f)
{
    if (Disabled(owner)) return false;
    jmp_buf jb;
    jmp_buf* outer = gGuard;
    if (setjmp(jb) == 0)
    {
        gGuard = &jb;
        f();
        gGuard = outer;
        return true;
    }
    gGuard = outer;
    DisableMod(owner, where);
    return false;
}

// ---- ddraw forwarding ---------------------------------------------------------------------------------------------
// exports the system ddraw.dll doesn't have (Windows-only ones under Wine and vice versa): never called by the game
HMODULE gReal; int gMissing;

void LoadRealDdraw()
{
    char sys[MAX_PATH];
    GetSystemDirectoryA(sys, MAX_PATH);
    std::string path = std::string(sys) + "\\ddraw.dll";
    gReal = LoadLibraryA(path.c_str());
    for (int i = 0; i < g_real_count; i++)
    {
        FARPROC p = gReal ? GetProcAddress(gReal, g_real_names[i]) : nullptr;
        g_real[i] = p ? (void*)p : g_missing[i];
        if (!p) gMissing++;
    }
}

// ---- game check -------------------------------------------------------------------------------------------------
// The running exe's code (in memory, before any hook) must be the build our addresses are for.
bool GameMatches(const std::string& exe)
{
    auto base = reinterpret_cast<const unsigned char*>(GetModuleHandleA(nullptr));
    auto dos = reinterpret_cast<const IMAGE_DOS_HEADER*>(base);
    auto nt = reinterpret_cast<const IMAGE_NT_HEADERS32*>(base + dos->e_lfanew);
    if ((uintptr_t)base != 0x400000 || nt->OptionalHeader.SizeOfImage != GAME_IMAGE_SIZE)
    {
        Log("exe %s: base %p, image size %lx: not the game build these mods are for", exe.c_str(), (void*)base, nt->OptionalHeader.SizeOfImage);
        return false;
    }
    uint64_t h = 0xcbf29ce484222325ULL;
    for (const unsigned char* p = base + GAME_TEXT_RVA; p < base + GAME_TEXT_RVA + GAME_TEXT_SIZE; p++) h = (h ^ *p) * 0x100000001b3ULL;
    Log("exe %s: code hash %016llx", exe.c_str(), (unsigned long long)h);
    return h == GAME_TEXT_HASH;
}

// The game's folder: the exe's, or for the Steam release the folder its launcher passes as -changedir= (the game
// itself runs from ProgramData\PopCap Games\Insaniquarium\popcapgame1.exe).
std::string GameFolder(const std::string& exeDir)
{
    std::string cmd = GetCommandLineA();
    size_t at = cmd.find("-changedir=");
    if (at == std::string::npos) return exeDir;
    std::string d = cmd.substr(at + 11);
    if (!d.empty() && d[0] == '"') d.erase(0, 1);
    size_t q = d.find('"');
    if (q != std::string::npos) d.erase(q);
    while (!d.empty() && (d.back() == ' ' || d.back() == '\\' || d.back() == '/')) d.pop_back();
    return d.empty() ? exeDir : d;
}

// ---- game helpers -------------------------------------------------------------------------------------------------
using namespace game;

void* App() { return *reinterpret_cast<void**>(gApp); }
void* CurrentBoard() { void* a = App(); return a ? at<void*>(a, App_mBoard) : nullptr; }
void* Font10() { return *reinterpret_cast<void**>(FONT_JUNGLEFEVER10OUTLINE); }

Color ToColor(unsigned argb) { return Color{ int((argb >> 16) & 255), int((argb >> 8) & 255), int(argb & 255), int(argb >> 24) }; }

using SetColorFn = void(__thiscall*)(void*, const Color*);
using SetFontFn = void(__thiscall*)(void*, void*);
using FillRectFn = void(__thiscall*)(void*, int, int, int, int);
using DrawStringFn = void(__thiscall*)(void*, const MsvcString*, int, int);
using StringWidthFn = int(__thiscall*)(void*, const MsvcString*);

void FillRect(void* g, int x, int y, int w, int h, unsigned argb)
{
    Color saved = at<Color>(g, Graphics_mColor), c = ToColor(argb);
    reinterpret_cast<SetColorFn>(Graphics_SetColor)(g, &c);
    reinterpret_cast<FillRectFn>(Graphics_FillRect)(g, x, y, w, h);
    at<Color>(g, Graphics_mColor) = saved;
}

void DrawText(void* g, const char* text, int x, int y, unsigned argb)
{
    void* font = Font10();
    if (!font) return;
    Color saved = at<Color>(g, Graphics_mColor), c = ToColor(argb);
    void* savedFont = at<void*>(g, Graphics_mFont);
    reinterpret_cast<SetFontFn>(Graphics_SetFont)(g, font);
    reinterpret_cast<SetColorFn>(Graphics_SetColor)(g, &c);
    MsvcString s = MakeString(text);
    reinterpret_cast<DrawStringFn>(Graphics_DrawString)(g, &s, x, y);
    at<Color>(g, Graphics_mColor) = saved;
    at<void*>(g, Graphics_mFont) = savedFont;
}

int TextWidth(const char* text)
{
    void* font = Font10();
    if (!font) return 0;
    MsvcString s = MakeString(text);
    void** vt = *reinterpret_cast<void***>(font);
    return reinterpret_cast<StringWidthFn>(vt[Font_vStringWidth / 4])(font, &s);
}

int ConfigIntIn(const char* section, const char* key, int def);
// The settings file kept in memory: reading it from disk for every setting (several mods do every frame, the settings
// page once per row) made menus slow, under Wine most of all. Read again when the file changes on disk (checked at most
// once a second, so edits in a text editor still apply), written through by config_set.
std::map<std::string, std::string> gIni;   // "section\nkey" in lower case -> value (trimmed, outer quotes removed)
FILETIME gIniTime;
DWORD gIniChecked;
bool gIniLoaded;
std::string IniPath() { return gModsDir + "\\remastered-mod.ini"; }
std::string IniKey(const char* section, const char* key)
{
    std::string k = std::string(section ? section : "") + "\n" + (key ? key : "");
    for (auto& c : k) c = (char)tolower((unsigned char)c);
    return k;
}
std::string TrimmedValue(std::string v)
{
    size_t a = v.find_first_not_of(" \t"), b = v.find_last_not_of(" \t\r");
    v = a == std::string::npos ? "" : v.substr(a, b - a + 1);
    if (v.size() >= 2 && v.front() == '"' && v.back() == '"') v = v.substr(1, v.size() - 2);
    return v;
}
void IniLoad()
{
    gIni.clear();
    FILE* f = fopen(IniPath().c_str(), "rb");
    if (!f) return;
    std::string text;
    char buf[4096];
    for (size_t n; (n = fread(buf, 1, sizeof buf, f)) > 0;) text.append(buf, n);
    fclose(f);
    if (text.compare(0, 3, "\xEF\xBB\xBF") == 0) text.erase(0, 3);
    std::string section;
    size_t pos = 0;
    while (pos < text.size())
    {
        size_t e = text.find('\n', pos);
        std::string line = text.substr(pos, e == std::string::npos ? std::string::npos : e - pos);
        pos = e == std::string::npos ? text.size() : e + 1;
        std::string t = TrimmedValue(line);
        if (t.empty() || t[0] == ';' || t[0] == '#') continue;
        if (t[0] == '[') { size_t c = t.find(']'); section = t.substr(1, c == std::string::npos ? std::string::npos : c - 1); continue; }
        size_t eq = t.find('=');
        if (eq == std::string::npos) continue;
        std::string k = IniKey(section.c_str(), TrimmedValue(t.substr(0, eq)).c_str());
        if (!gIni.count(k)) gIni[k] = TrimmedValue(t.substr(eq + 1));   // the first one counts, as in Windows
    }
}
void IniFresh()
{
    DWORD now = GetTickCount();
    if (gIniLoaded && now - gIniChecked < 1000) return;
    gIniChecked = now;
    WIN32_FILE_ATTRIBUTE_DATA a{};
    bool ok = GetFileAttributesExA(IniPath().c_str(), GetFileExInfoStandard, &a) != 0;
    if (gIniLoaded && ok && CompareFileTime(&a.ftLastWriteTime, &gIniTime) == 0) return;
    gIniTime = ok ? a.ftLastWriteTime : FILETIME{};
    gIniLoaded = true;
    IniLoad();
}
const std::string* IniGet(const char* section, const char* key)
{
    IniFresh();
    auto it = gIni.find(IniKey(section, key));
    return it == gIni.end() ? nullptr : &it->second;
}
int ConfigInt(const char* section, const char* key, int def)
{
    const std::string* v = IniGet(section, key);
    return v ? (int)strtol(v->c_str(), nullptr, 10) : def;
}

// Several mods (or the core and a mod) may hook the same game function: MinHook allows one hook per address, so a
// second hook goes on the previous detour instead (game -> newest detour -> ... -> first detour -> the game's code).
std::vector<std::pair<void*, void*>> gHooked;   // game function -> its newest detour

int ConfigIntIn(const char* section, const char* key, int def) { return ConfigInt(section, key, def); }

int Hook(void* target, void* detour, void** original)
{
    void* at = target;
    for (auto& h : gHooked) if (h.first == target) at = h.second;
    if (MH_CreateHook(at, detour, original) != MH_OK) { Log("hook %p failed to create", target); return 0; }
    if (MH_EnableHook(at) != MH_OK) { Log("hook %p failed to enable", target); return 0; }
    bool found = false;
    for (auto& h : gHooked) if (h.first == target) { h.second = detour; found = true; }
    if (!found) gHooked.push_back({ target, detour });
    return 1;
}

void Toast(const char* text) { gToast = text; gToastUntil = 0; gToastUntilInput = false; gToastTop = false; gRedraw = true; Log("toast: %s", text); }   // 3 s from when it first shows
void Redraw() { gRedraw = true; }
void MousePos(int* x, int* y) { if (x) *x = gMouseX; if (y) *y = gMouseY; }
void PlayGameSound(int id)
{
    void* b = CurrentBoard();
    if (b) reinterpret_cast<void(__thiscall*)(void*, int, int, double)>(Board_PlaySample)(b, id, 3, 1.0);
}
void DrawImage(void* g, void* img, int x, int y)
{
    if (img) reinterpret_cast<void(__thiscall*)(void*, void*, int, int)>(Graphics_DrawImage)(g, img, x, y);
}
void DrawImagePart(void* g, void* img, int x, int y, int sx, int sy, int sw, int sh)
{
    int src[4] = { sx, sy, sw, sh };
    if (img) reinterpret_cast<void(__thiscall*)(void*, void*, int, int, const int*)>(Graphics_DrawImageSrc)(g, img, x, y, src);
}
// Graphics +0x08/+0x0c mTransX/Y, +0x10/+0x14 mScaleX/Y, +0x18/+0x1c mScaleOrigX/Y (floats; DrawImageSrc @00455e40
// stretches when the scale isn't 1): set for one draw and put back
void DrawImageScaled(void* g, void* img, int x, int y, int sx, int sy, int sw, int sh, float scale)
{
    if (!g || !img || scale <= 0) return;
    float* f = reinterpret_cast<float*>(static_cast<char*>(g) + 0x10);
    float saved[4] = { f[0], f[1], f[2], f[3] };
    f[0] = f[1] = scale;
    f[2] = x + at<float>(g, 0x08); f[3] = y + at<float>(g, 0x0c);
    DrawImagePart(g, img, x, y, sx, sy, sw, sh);
    f[0] = saved[0]; f[1] = saved[1]; f[2] = saved[2]; f[3] = saved[3];
}
void DrawTextFont(void* g, void* font, const char* text, int x, int y, unsigned argb)
{
    if (!font) font = Font10();
    if (!font) return;
    Color saved = at<Color>(g, Graphics_mColor), c = ToColor(argb);
    void* savedFont = at<void*>(g, Graphics_mFont);
    reinterpret_cast<SetColorFn>(Graphics_SetColor)(g, &c);
    reinterpret_cast<SetFontFn>(Graphics_SetFont)(g, font);
    MsvcString s = MakeString(text);
    reinterpret_cast<DrawStringFn>(Graphics_DrawString)(g, &s, x, y);
    at<Color>(g, Graphics_mColor) = saved;
    at<void*>(g, Graphics_mFont) = savedFont;
}
int TextWidthFont(void* font, const char* text)
{
    if (!font) font = Font10();
    if (!font) return 0;
    MsvcString s = MakeString(text);
    void** vt = *reinterpret_cast<void***>(font);
    return reinterpret_cast<StringWidthFn>(vt[Font_vStringWidth / 4])(font, &s);
}
void ConfigSet(const char* section, const char* key, const char* value)
{
    WritePrivateProfileStringA(section, key, value, IniPath().c_str());
    IniFresh();
    if (value) gIni[IniKey(section, key)] = TrimmedValue(value); else gIni.erase(IniKey(section, key));
    WIN32_FILE_ATTRIBUTE_DATA a{};   // our own write: no need to read the file again
    if (GetFileAttributesExA(IniPath().c_str(), GetFileExInfoStandard, &a)) gIniTime = a.ftLastWriteTime;
}
int ModList(int i, const char** name, const char** description)
{
    if (i < 0 || i >= (int)gMods.size()) return -1;
    if (name) *name = gMods[i].name.c_str();
    if (description) *description = gMods[i].description.c_str();
    return gMods[i].state;
}

// Restarting: the game allows one copy at a time, so a helper waits for this process to end and then starts the game
// again: rundll32 runs this DLL's RemodRelaunch export ("<pid>|<folder>|<command line>").
void Restart()
{
    void* a = App();
    if (a && at<void*>(a, App_mProfile)) reinterpret_cast<bool(__thiscall*)(void*)>(App_SaveProfile)(a);
    char self[MAX_PATH], dir[MAX_PATH], sys[MAX_PATH];
    HMODULE me;
    GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS | GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT, (LPCSTR)&Restart, &me);
    GetModuleFileNameA(me, self, MAX_PATH);
    GetCurrentDirectoryA(MAX_PATH, dir);
    GetSystemDirectoryA(sys, MAX_PATH);
    std::string cmd = std::string("\"") + sys + "\\rundll32.exe\" \"" + self + "\",RemodRelaunch " +
                      std::to_string(GetCurrentProcessId()) + "|" + dir + "|" + GetCommandLineA();
    STARTUPINFOA si{ sizeof si };
    PROCESS_INFORMATION pi{};
    if (!CreateProcessA(nullptr, &cmd[0], nullptr, nullptr, FALSE, 0, nullptr, dir, &si, &pi))
    {
        Log("restart: couldn't start the helper (error %lu)", GetLastError());
        Toast("Couldn't restart: please restart the game yourself");
        return;
    }
    CloseHandle(pi.hThread); CloseHandle(pi.hProcess);
    Log("restart: the game closes and starts again");
    if (a) reinterpret_cast<void(__thiscall*)(void*)>((*reinterpret_cast<void***>(a))[App_vShutdown / 4])(a);   // as the Quit button
}

void Restart();
void SetInputFilter(int (*cb)(unsigned, unsigned, long)) { gInputFilter = cb; gInputFilterOwner = cb ? ModuleOf((void*)cb) : nullptr; }

// the game's own handling: its window procedure queues the message (SexyAppBase deferred messages, list at app +0x35c),
// and ProcessDeferredMessages (@004846c0, stdcall(app), one message a call) handles it now
void InjectInput(unsigned msg, unsigned wp, long lp)
{
    void* a = App();
    HWND w = a ? at<HWND>(a, 0x350) : nullptr;
    if (!a || !w || !gOrigWndProc) return;
    CallWindowProcA(gOrigWndProc, w, msg, wp, lp);
    for (int guard = 0; at<uint32_t>(a, App_mDeferredCount) > 0 && guard < 64; guard++)
        reinterpret_cast<bool(__stdcall*)(void*)>(App_ProcessDeferredMessage)(a);
}

void ConfigChanged()
{
    Log("settings changed");
    for (auto& cb : gConfig) Guarded(cb.owner, "on_config", [&] { cb.fn(); });
}
// ini files have no inline comments, but people write them ("window=native   ; ..."): cut at ';' and trim
void Trim(char* s)
{
    if (char* c = strchr(s, ';')) *c = 0;
    size_t n = strlen(s);
    while (n && (s[n - 1] == ' ' || s[n - 1] == '\t')) s[--n] = 0;
    size_t i = 0;
    while (s[i] == ' ' || s[i] == '\t') i++;
    if (i) memmove(s, s + i, n - i + 1);
}
void ConfigString(const char* section, const char* key, const char* def, char* out, int size)
{
    if (!out || size <= 0) return;
    const std::string* v = IniGet(section, key);
    const char* src = v ? v->c_str() : (def ? def : "");
    strncpy(out, src, size - 1);
    out[size - 1] = 0;
    Trim(out);
}

RemodApi gApi = {
    REMOD_API_VERSION,
    Log,
    Hook,
    [](void (*cb)(void*)) { gTick.push_back({cb, ModuleOf((void*)cb)}); },
    [](void (*cb)(void*, void*)) { gDraw.push_back({cb, ModuleOf((void*)cb)}); },
    [](int (*cb)(int, int)) { gKey.push_back({cb, ModuleOf((void*)cb)}); },
    App,
    CurrentBoard,
    FillRect,
    DrawText,
    TextWidth,
    ConfigInt,
    Toast,
    [](void (*cb)(void*)) { gOverlay.push_back({cb, ModuleOf((void*)cb)}); },
    Redraw,
    [](int (*cb)(int, int, int, int)) { gMouse.push_back({cb, ModuleOf((void*)cb)}); },
    MousePos,
    PlayGameSound,
    ConfigString,
    DrawImage,
    DrawImagePart,
    DrawTextFont,
    TextWidthFont,
    ConfigSet,
    ConfigChanged,
    [](void (*cb)(void)) { gConfig.push_back({cb, ModuleOf((void*)cb)}); },
    ModList,
    Restart,
    SetInputFilter,
    InjectInput,
    [](unsigned* out) { return DisplayCaptureFrame(out) ? 1 : 0; },
    DrawImageScaled,
};

// ---- hooks ----------------------------------------------------------------------------------------------------
using BoardUpdateFn = void(__thiscall*)(void*);
using BoardDrawFn = void(__thiscall*)(void*, void*);
BoardUpdateFn oBoardUpdate;
BoardDrawFn oBoardDraw;

void EnsureWindowHooked();

void __fastcall BoardUpdate(void* board, void*)
{
    oBoardUpdate(board);
    EnsureWindowHooked();
    for (auto& cb : gTick) Guarded(cb.owner, "on_tick", [&] { cb.fn(board); });
}

void __fastcall BoardDraw(void* board, void*, void* g)
{
    oBoardDraw(board, g);
    for (auto& cb : gDraw) Guarded(cb.owner, "on_draw", [&] { cb.fn(board, g); });
}

// ---- the overlay: after WidgetManager::DrawScreen, on top of every widget ------------------------------------------
using MarkAllDirtyFn = void(__thiscall*)(void*);
using GraphicsCtorFn = void*(__thiscall*)(void*, void*);
using GraphicsDtorFn = void(__thiscall*)(void*);

void MarkAllDirty(void* wm)
{
    void** vt = *reinterpret_cast<void***>(wm);
    reinterpret_cast<MarkAllDirtyFn>(vt[Container_vMarkAllDirty / 4])(wm);
}

// every update tick, before the game's own: the native window's switch from fullscreen (between frames, not while drawing)
using UpdateFramesFn = void(__thiscall*)(void*);
UpdateFramesFn oUpdateFrames;
void __fastcall UpdateFrames(void* app, void*)
{
    if (DisplayNeedsSwitch())
    {
        Log("native window: switching the game to windowed");
        reinterpret_cast<void(__thiscall*)(void*, bool)>((*reinterpret_cast<void***>(app))[App_vSwitchScreenMode / 4])(app, true);
    }
    oUpdateFrames(app);
}

extern "C" void* oDrawScreen;
void* oDrawScreen;

// called by the asm detour below with the widget manager and DrawScreen's result
extern "C" void __cdecl AfterDrawScreen(void* wm, int drew)
{
    EnsureWindowHooked();   // from the first frame (title screen and menus), not just once a level runs
    bool toast = !gToast.empty();
    if (toast && drew & 0xff && !gToastUntil && !gToastUntilInput) gToastUntil = GetTickCount() + 3000;
    if (toast && gToastUntil && GetTickCount() >= gToastUntil) { gToast.clear(); toast = false; gRedraw = true; }
    if (drew & 0xff && (toast || !gOverlay.empty()))
    {
        void* img = at<void*>(wm, WM_mImage);
        alignas(8) unsigned char gbuf[Graphics_size + 16];
        void* g = gbuf;
        reinterpret_cast<GraphicsCtorFn>(Graphics_ctorImage)(g, img);
        for (auto& cb : gOverlay) Guarded(cb.owner, "on_overlay", [&] { cb.fn(g); });
        if (toast)
        {
            int w = TextWidth(gToast.c_str()) + 24;
            int y = gToastTop ? 6 : 396;
            FillRect(g, (640 - w) / 2, y, w, 26, 0xc0101840);
            DrawText(g, gToast.c_str(), (640 - w) / 2 + 12, y + 18, 0xffffff80);
        }
        reinterpret_cast<GraphicsDtorFn>(Graphics_dtor)(g);
    }
    if (gRedraw) { gRedraw = false; MarkAllDirty(wm); }
}

// DrawScreen takes `this` in EDI (not ECX) and returns a bool in AL: keep EDI for the original, then pass it on
extern "C" void DrawScreenDetour();
asm(R"(
    .text
    .globl _DrawScreenDetour
_DrawScreenDetour:
    push %edi
    call *_oDrawScreen
    pop %edi
    push %eax
    movzbl %al, %eax
    push %eax
    push %edi
    call _AfterDrawScreen
    add $8, %esp
    pop %eax
    ret
)");

LRESULT CALLBACK WndProc(HWND h, UINT msg, WPARAM wp, LPARAM lp)
{
    if (gToastUntilInput && (msg == WM_LBUTTONDOWN || msg == WM_RBUTTONDOWN || msg == WM_KEYDOWN))
    {
        gToastUntilInput = false;
        gToastUntil = GetTickCount() + 1500;
    }
    bool down = msg == WM_KEYDOWN || msg == WM_SYSKEYDOWN, up = msg == WM_KEYUP || msg == WM_SYSKEYUP;
    if ((down && !(lp & (1 << 30))) || up)   // presses (not auto-repeat) and releases
        for (auto& cb : gKey)
        {
            int handled = 0;
            Guarded(cb.owner, "on_key", [&] { handled = cb.fn((int)wp, down ? 1 : 0); });
            if (handled) return 0;
        }
    // native window: mouse positions in the big window -> the game's 640x480 (the wheel's are screen positions)
    if (((msg >= WM_MOUSEFIRST && msg <= WM_MBUTTONDBLCLK) && msg != WM_MOUSEWHEEL) && DisplayActive()) lp = DisplayMapMouse(lp);
    bool input = (msg >= WM_MOUSEFIRST && msg <= WM_MOUSELAST) || (msg >= WM_KEYFIRST && msg <= WM_KEYLAST);
    if (input && gInputFilter)
    {
        int keep = 0;
        if (msg >= WM_MOUSEFIRST && msg <= WM_MBUTTONDBLCLK && msg != WM_MOUSEWHEEL) { gMouseX = (short)LOWORD(lp); gMouseY = (short)HIWORD(lp); }
        Guarded(gInputFilterOwner, "input filter", [&] { keep = gInputFilter(msg, (unsigned)wp, (long)lp); });
        if (keep) return 0;
    }
    if (msg >= WM_MOUSEFIRST && msg <= WM_MBUTTONDBLCLK && msg != WM_MOUSEWHEEL)
    {
        gMouseX = (short)LOWORD(lp); gMouseY = (short)HIWORD(lp);
        int button = -1, down = 0;
        switch (msg)
        {
            case WM_LBUTTONDOWN: case WM_LBUTTONDBLCLK: button = 0; down = 1; break;
            case WM_LBUTTONUP: button = 0; break;
            case WM_RBUTTONDOWN: case WM_RBUTTONDBLCLK: button = 1; down = 1; break;
            case WM_RBUTTONUP: button = 1; break;
            case WM_MBUTTONDOWN: case WM_MBUTTONDBLCLK: button = 2; down = 1; break;
            case WM_MBUTTONUP: button = 2; break;
        }
        if (button >= 0)
        {
            if (!down && gSwallowUp[button]) { gSwallowUp[button] = false; return 0; }
            for (auto& cb : gMouse)
            {
                int handled = 0;
                Guarded(cb.owner, "on_mouse", [&] { handled = cb.fn(gMouseX, gMouseY, button, down); });
                if (handled) { if (down) gSwallowUp[button] = true; return 0; }
            }
        }
    }
    return CallWindowProcA(gOrigWndProc, h, msg, wp, lp);
}

void LoadMods()
{
    WIN32_FIND_DATAA fd;
    HANDLE it = FindFirstFileA((gModsDir + "\\*.dll").c_str(), &fd);
    if (it == INVALID_HANDLE_VALUE) { Log("no mods in %s", gModsDir.c_str()); return; }
    int n = 0;
    do
    {
        std::string path = gModsDir + "\\" + fd.cFileName;
        std::string name = fd.cFileName;
        name = name.substr(0, name.size() - 4);
        if (!ConfigIntIn("mods", name.c_str(), 1)) { Log("%s: switched off ([mods] %s=0)", fd.cFileName, name.c_str()); gMods.push_back({ name, "", REMOD_MOD_OFF, nullptr }); continue; }
        HMODULE m = LoadLibraryA(path.c_str());
        auto init = m ? reinterpret_cast<RemodInitFn>(GetProcAddress(m, "RemodInit")) : nullptr;
        if (!init) { Log("%s: not a mod (%s)", fd.cFileName, m ? "no RemodInit" : "load failed"); gMods.push_back({ name, "", REMOD_MOD_BROKEN, m }); continue; }
        std::string description;
        if (auto describe = reinterpret_cast<RemodDescribeFn>(GetProcAddress(m, "RemodDescribe"))) { const char* d = describe(); if (d) description = d; }
        gMods.push_back({ name, description, REMOD_MOD_DECLINED, m });
        size_t slot = gMods.size() - 1;
        int ok = 0;
        if (!Guarded(m, "RemodInit", [&] { ok = init(&gApi); })) continue;
        if (ok) { n++; gMods[slot].state = REMOD_MOD_ON; Log("%s: loaded", fd.cFileName); }
        else Log("%s: declined to load", fd.cFileName);
    } while (FindNextFileA(it, &fd));
    FindClose(it);
    Log("%d mod(s) loaded", n);
    // shown on the title screen, so players can see the mod is installed
    char t[96];
    snprintf(t, sizeof t, "Insaniquarium - Remastered Mod is on (%d mod%s)", n, n == 1 ? "" : "s");
    Toast(t);
    gToastUntilInput = true;   // past the loading screen: until the player first clicks
    gToastTop = true;
}

// copies a folder tree (for the save backup)
bool CopyTree(const std::string& from, const std::string& to)
{
    CreateDirectoryA(to.c_str(), nullptr);
    WIN32_FIND_DATAA fd;
    HANDLE it = FindFirstFileA((from + "\\*").c_str(), &fd);
    if (it == INVALID_HANDLE_VALUE) return false;
    bool ok = true;
    do
    {
        std::string n = fd.cFileName;
        if (n == "." || n == "..") continue;
        if (fd.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) ok &= CopyTree(from + "\\" + n, to + "\\" + n);
        else ok &= CopyFileA((from + "\\" + n).c_str(), (to + "\\" + n).c_str(), FALSE) != 0;
    } while (FindNextFileA(it, &fd));
    FindClose(it);
    return ok;
}

// the first time mods run, keep a copy of the player's saves (userdata in the game's data folder: ProgramData\PopCap
// Games\Insaniquarium, or ProgramData\Steam\Insaniquarium for the Steam release)
void BackupSaves()
{
    char base[MAX_PATH];
    if (SHGetFolderPathA(nullptr, CSIDL_COMMON_APPDATA, nullptr, 0, base) != S_OK) return;
    std::string old = std::string(base) + "\\PopCap Games\\Insaniquarium";
    std::string dir = ReadString(G_AppDataFolder);
    while (!dir.empty() && (dir.back() == '\\' || dir.back() == '/')) dir.pop_back();
    if (dir.empty()) dir = old;
    std::string saves = dir + "\\userdata", backup = dir + "\\userdata-before-remastered-mod";
    // earlier versions kept the mods' own files (achievements, records, layouts) in PopCap Games\Insaniquarium\userdata
    // even for the Steam release: move them over to where the game saves (never over a newer file)
    if (_stricmp(dir.c_str(), old.c_str()) != 0)
    {
        WIN32_FIND_DATAA fd;
        HANDLE it = FindFirstFileA((old + "\\userdata\\*.txt").c_str(), &fd);
        if (it != INVALID_HANDLE_VALUE)
        {
            CreateDirectoryA(saves.c_str(), nullptr);
            do
                if (CopyFileA((old + "\\userdata\\" + fd.cFileName).c_str(), (saves + "\\" + fd.cFileName).c_str(), TRUE))
                    Log("copied %s from %s\\userdata", fd.cFileName, old.c_str());
            while (FindNextFileA(it, &fd));
            FindClose(it);
        }
    }
    if (GetFileAttributesA(saves.c_str()) == INVALID_FILE_ATTRIBUTES) { Log("no saves yet (%s)", saves.c_str()); return; }
    if (GetFileAttributesA(backup.c_str()) != INVALID_FILE_ATTRIBUTES) return;   // made on an earlier run
    Log(CopyTree(saves, backup) ? "saves backed up to %s" : "couldn't back up the saves to %s", backup.c_str());
}

bool gModsLoaded;
void EnsureModsLoaded()
{
    if (gModsLoaded || !gActive) return;
    gModsLoaded = true;
    BackupSaves();
    LoadMods();
}

// the game window's messages, for the key callbacks, the native window's mouse mapping and the start-up toast
// (subclassed once the window exists)
void EnsureWindowHooked()
{
    if (gOrigWndProc || !App()) return;
    HWND wnd = at<HWND>(App(), 0x350);   // SexyAppBase::mHWnd (SetTimer(this->f_350, ...))
    if (wnd) DisplaySetWindow(wnd);
    if (wnd) { gOrigWndProc = (WNDPROC)SetWindowLongPtrA(wnd, GWLP_WNDPROC, (LONG_PTR)WndProc); Log("window %p hooked", (void*)wnd); }
}

void Start(HMODULE self)
{
    char path[MAX_PATH];
    GetModuleFileNameA(nullptr, path, MAX_PATH);
    std::string exe = path;
    // loaded by rundll32 for RemodRelaunch (or by any other program that isn't the game): do nothing, write nothing
    std::string file = exe.substr(exe.find_last_of("\\/") + 1);
    for (auto& ch : file) ch = (char)tolower(ch);
    if (file == "rundll32.exe") return;
    gGameDir = GameFolder(exe.substr(0, exe.find_last_of("\\/")));
    gModsDir = gGameDir + "\\mods";
    CreateDirectoryA(gModsDir.c_str(), nullptr);
    // the game's own screensaver (WinFish_Scr.exe) loads this DLL too and is turned away by the game check below: it adds to
    // the log instead of starting it again, so the game's log is kept
    gLog = fopen((gModsDir + "\\remastered-mod.log").c_str(), file == "winfish_scr.exe" ? "a" : "w");
    Log("Insaniquarium - Remastered Mod core (API %d)", REMOD_API_VERSION);
    char rp[MAX_PATH] = "";
    if (gReal) GetModuleFileNameA(gReal, rp, MAX_PATH);
    Log("system ddraw: %s (%d of %d exports not there)", gReal ? rp : "NOT FOUND", gMissing, g_real_count);
    (void)self;
    if (!GameMatches(exe)) { Log("not the Insaniquarium Deluxe 1.1 game these mods are for: mods stay off"); return; }
    // safe mode: Shift held while the game starts, or [core] enabled=0
    if (GetAsyncKeyState(VK_SHIFT) & 0x8000) { Log("Shift held at start: safe mode, mods stay off"); return; }
    if (!ConfigInt("core", "enabled", 1)) { Log("[core] enabled=0 in remastered-mod.ini: mods stay off"); return; }
    AddVectoredExceptionHandler(1, FaultHandler);
    if (MH_Initialize() != MH_OK) { Log("MinHook failed to start"); return; }
    gActive = Hook((void*)Board_Update, (void*)&BoardUpdate, (void**)&oBoardUpdate)
           && Hook((void*)Board_Draw, (void*)&BoardDraw, (void**)&oBoardDraw)
           && Hook((void*)WidgetManager_DrawScreen, (void*)&DrawScreenDetour, &oDrawScreen)
           && Hook((void*)App_UpdateFrames, (void*)&UpdateFrames, (void**)&oUpdateFrames);
    Log(gActive ? "hooks installed" : "hooks failed: mods stay off");
    if (gActive) DisplayInit();
}

}  // namespace

// for core/display.cpp
void CoreLog(const char* fmt, ...)
{
    char b[512];
    va_list a; va_start(a, fmt); vsnprintf(b, sizeof b, fmt, a); va_end(a);
    Log("%s", b);
}
int CoreConfigInt(const char* section, const char* key, int def) { return ConfigInt(section, key, def); }
std::string CoreConfigString(const char* section, const char* key, const char* def)
{
    char b[256];
    ConfigString(section, key, def, b, sizeof b);
    return b;
}
void CoreToast(const char* text) { Toast(text); }
bool CoreGameWindowed() { void* a = App(); return a && at<bool>(a, App_mIsWindowed); }

// the game's DirectDraw entry points: load the mods first (main thread, outside the loader lock), then the real thing
extern "C" HRESULT WINAPI Own_DirectDrawCreate(void* guid, void** dd, void* outer)
{
    EnsureModsLoaded();
    using Fn = HRESULT(WINAPI*)(void*, void**, void*);
    auto real = gReal ? (Fn)GetProcAddress(gReal, "DirectDrawCreate") : nullptr;
    HRESULT r = real ? real(guid, dd, outer) : E_FAIL;
    if (r == 0 && gActive && dd && *dd) DisplayOnDirectDraw(nullptr, *dd);
    return r;
}

extern "C" HRESULT WINAPI Own_DirectDrawCreateEx(void* guid, void** dd, const void* iid, void* outer)
{
    EnsureModsLoaded();
    using Fn = HRESULT(WINAPI*)(void*, void**, const void*, void*);
    auto real = gReal ? (Fn)GetProcAddress(gReal, "DirectDrawCreateEx") : nullptr;
    HRESULT r = real ? real(guid, dd, iid, outer) : E_FAIL;
    if (r == 0 && gActive && dd && *dd) DisplayOnDirectDraw(*dd, nullptr);
    return r;
}

// rundll32 "<this dll>",RemodRelaunch <pid>|<folder>|<command line>: waits for the game (pid) to end, then starts it again
extern "C" void CALLBACK RemodRelaunch(HWND, HINSTANCE, LPSTR args, int)
{
    std::string s = args ? args : "";
    size_t a = s.find('|'), b = a == std::string::npos ? a : s.find('|', a + 1);
    if (b == std::string::npos) return;
    DWORD pid = strtoul(s.substr(0, a).c_str(), nullptr, 10);
    std::string dir = s.substr(a + 1, b - a - 1), cmd = s.substr(b + 1);
    if (HANDLE p = OpenProcess(SYNCHRONIZE, FALSE, pid)) { WaitForSingleObject(p, 60000); CloseHandle(p); }
    Sleep(500);   // let the game's single-instance lock go
    STARTUPINFOA si{ sizeof si };
    PROCESS_INFORMATION pi{};
    if (CreateProcessA(nullptr, &cmd[0], nullptr, nullptr, FALSE, 0, nullptr, dir.c_str(), &si, &pi)) { CloseHandle(pi.hThread); CloseHandle(pi.hProcess); }
}

extern "C" BOOL WINAPI DllMain(HINSTANCE inst, DWORD reason, LPVOID)
{
    if (reason == DLL_PROCESS_ATTACH)
    {
        DisableThreadLibraryCalls(inst);
        LoadRealDdraw();
        Start(inst);
    }
    else if (reason == DLL_PROCESS_DETACH)
    {
        if (gActive) DisplayAtExit();
        Log("game closed");
    }
    return TRUE;
}
