#!/usr/bin/env python3
"""Generates the ddraw.dll proxy's exports from loader/ddraw.exports (one export per line: name and stdcall argument bytes). Every export becomes
a jump through g_real[i], filled at load time from the system's ddraw.dll, except the ones the core implements itself
(OWN below), which are exported from core.cpp as Own_<name>. For an export the system ddraw.dll lacks, g_missing[i] is a
stand-in that returns E_NOTIMPL and pops the export's argument bytes (the number after its name).
  gen-proxy.py OUTDIR  ->  OUTDIR/proxy_stubs.S, OUTDIR/proxy_names.c, OUTDIR/proxy.def"""
import os, sys

OWN = ('DirectDrawCreate', 'DirectDrawCreateEx')
EXTRA = {'RemodRelaunch': 16}   # the core's own exports (not DirectDraw): restarting the game through rundll32
here = os.path.dirname(os.path.abspath(__file__))
rows = [l.split() for l in open(os.path.join(here, '..', 'loader', 'ddraw.exports')) if l.strip() and not l.startswith('#')]
names = [r[0] for r in rows]
args = {r[0]: int(r[1]) for r in rows}
out = sys.argv[1]
os.makedirs(out, exist_ok=True)

with open(os.path.join(out, 'proxy_stubs.S'), 'w') as f:
    f.write('# generated by tools/gen-proxy.py\n\t.text\n')
    for i, n in enumerate(names):
        if n not in OWN:
            f.write(f'\t.globl _p_{n}\n_p_{n}:\n\tjmp *_g_real+{4 * i}\n')
            f.write(f'_m_{n}:\n\tmovl $0x80004001, %eax\n\tret ${args[n]}\n')
    f.write('\t.section .rdata\n\t.globl _g_missing\n\t.align 4\n_g_missing:\n')
    f.write(''.join(f'\t.long 0\n' if n in OWN else f'\t.long _m_{n}\n' for n in names))
    f.write(f'\t.bss\n\t.globl _g_real\n\t.align 4\n_g_real:\n\t.space {4 * len(names)}\n')

with open(os.path.join(out, 'proxy_names.c'), 'w') as f:
    f.write('/* generated by tools/gen-proxy.py */\n')
    f.write(f'const int g_real_count = {len(names)};\n')
    f.write('const char* const g_real_names[] = {\n' + ''.join(f'  "{n}",\n' for n in names) + '};\n')

with open(os.path.join(out, 'proxy.def'), 'w') as f:
    f.write('LIBRARY ddraw.dll\nEXPORTS\n')
    f.write(''.join(f'  {n}=Own_{n}@{args[n]}\n' if n in OWN else f'  {n}=p_{n}\n' for n in names))
    f.write(''.join(f'  {n}={n}@{b}\n' for n, b in EXTRA.items()))
print(f'{len(names)} ddraw exports ({len(OWN)} implemented by the core)')
